site_name: LearnAI-with-Ray
theme:
  name: material
markdown_extensions:
  - admonition          # 基础提示框
  - pymdownx.details    # 支持 ??? 折叠
  - pymdownx.superfences # 必须：允许在折叠框里放代码块、列表或嵌套内容
  - obsidian_media_mkdocs
  - pymdownx.highlight:
      anchor_linenums: false
  - pymdownx.inlinehilite
  # - pymdownx.snippets
  - pymdownx.arithmatex
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/javascripts/collapse.js
extra_css:
  - assets/stylesheets/extra.css
plugins:
  - obsidian-bridge
  - callouts:
      breakless_lists: false
  - search
  - awesome-pages
site_url: https://ray-lei-17.github.io/LearnAI-with-Ray/
